package org.commonprovenance.framework.store.persistence.metaComponent.model.relation;

import org.commonprovenance.framework.store.persistence.metaComponent.model.node.EntityNode;
import org.springframework.data.annotation.PersistenceCreator;
import org.springframework.data.neo4j.core.schema.GeneratedValue;
import org.springframework.data.neo4j.core.schema.Id;
import org.springframework.data.neo4j.core.schema.RelationshipProperties;
import org.springframework.data.neo4j.core.schema.TargetNode;

@RelationshipProperties
public final class BundleEntities {

  @Id
  @GeneratedValue
  private final String id;

  @TargetNode
  private final EntityNode entity;

  // Constructor for full initialization (used by Neo4j when reading)
  @PersistenceCreator
  public BundleEntities(String id, EntityNode entity) {
    this.id = id;
    this.entity = entity;
  }

  // Constructor for creating new relationships (id will be generated)
  public BundleEntities(EntityNode entity) {
    this.id = null; // id will be generated by Neo4j
    this.entity = entity;
  }

  // Wither methods for immutability
  public BundleEntities withId(String id) {
    return new BundleEntities(id, this.getEntity());
  }

  public BundleEntities withEntity(EntityNode entit) {
    return new BundleEntities(this.getId(), entit);
  }

  // Getters
  public String getId() {
    return this.id;
  }

  public EntityNode getEntity() {
    return this.entity;
  }
}
