package org.commonprovenance.framework.store.persistence.metaComponent.model.relation;

import org.commonprovenance.framework.store.persistence.metaComponent.model.node.ActivityNode;
import org.springframework.data.annotation.PersistenceCreator;
import org.springframework.data.neo4j.core.schema.GeneratedValue;
import org.springframework.data.neo4j.core.schema.Id;
import org.springframework.data.neo4j.core.schema.RelationshipProperties;
import org.springframework.data.neo4j.core.schema.TargetNode;

import jakarta.validation.constraints.NotNull;

@RelationshipProperties
public final class BundleActivities {

  @Id
  @GeneratedValue
  private final Long id;

  @TargetNode
  private final ActivityNode activity;

  // Constructor for full initialization (used by Neo4j when reading)
  @PersistenceCreator
  public BundleActivities(Long id, ActivityNode activity) {
    this.id = id;
    this.activity = activity;
  }

  // Constructor for creating new relationships (id will be generated)
  public BundleActivities(ActivityNode activity) {
    this.id = null; // id will be generated by Neo4j
    this.activity = activity;
  }

  // Wither methods for immutability
  public @NotNull BundleActivities withId(Long id) {
    return new BundleActivities(id, this.getActivity());
  }

  public @NotNull BundleActivities withActivity(@NotNull ActivityNode activity) {
    return new BundleActivities(this.getId(), activity);
  }

  // Getters
  public Long getId() {
    return this.id;
  }

  public ActivityNode getActivity() {
    return this.activity;
  }
}
