package org.commonprovenance.framework.store.persistence.metaComponent.model.relation;

import org.commonprovenance.framework.store.persistence.metaComponent.model.node.AgentNode;
import org.springframework.data.annotation.PersistenceCreator;
import org.springframework.data.neo4j.core.schema.GeneratedValue;
import org.springframework.data.neo4j.core.schema.Id;
import org.springframework.data.neo4j.core.schema.RelationshipProperties;
import org.springframework.data.neo4j.core.schema.TargetNode;

import jakarta.validation.constraints.NotNull;

@RelationshipProperties
public final class BundleAgents {

  @Id
  @GeneratedValue
  private final Long id;

  @TargetNode
  private final AgentNode agent;

  // Constructor for full initialization (used by Neo4j when reading)
  @PersistenceCreator
  public BundleAgents(Long id, AgentNode agent) {
    this.id = id;
    this.agent = agent;
  }

  // Constructor for creating new relationships (id will be generated)
  public BundleAgents(AgentNode agent) {
    this.id = null; // id will be generated by Neo4j
    this.agent = agent;
  }

  // Wither methods for immutability
  public @NotNull BundleAgents withId(Long id) {
    return new BundleAgents(id, this.getAgent());
  }

  public @NotNull BundleAgents withAgetn(@NotNull AgentNode agent) {
    return new BundleAgents(this.getId(), agent);
  }

  // Getters
  public Long getId() {
    return this.id;
  }

  public AgentNode getAgent() {
    return this.agent;
  }
}
