package org.commonprovenance.framework.store.persistence.metaComponent.model.relation;

import org.commonprovenance.framework.store.persistence.metaComponent.model.node.BaseProvClassNode;
import org.springframework.data.annotation.PersistenceCreator;
import org.springframework.data.neo4j.core.schema.GeneratedValue;
import org.springframework.data.neo4j.core.schema.Id;
import org.springframework.data.neo4j.core.schema.RelationshipProperties;
import org.springframework.data.neo4j.core.schema.TargetNode;

import jakarta.validation.constraints.NotNull;

@RelationshipProperties
public final class Contains {

  @Id
  @GeneratedValue
  private final Long id;

  @TargetNode
  private final BaseProvClassNode node;

  // Constructor for full initialization (used by Neo4j when reading)
  @PersistenceCreator
  public Contains(Long id, BaseProvClassNode node) {
    this.id = id;
    this.node = node;
  }

  // Constructor for creating new relationships (id will be generated)
  public Contains(BaseProvClassNode node) {
    this.id = null; // id will be generated by Neo4j
    this.node = node;
  }

  // Wither methods for immutability
  public @NotNull Contains withId(Long id) {
    return new Contains(id, this.getNode());
  }

  public @NotNull Contains withDocument(@NotNull BaseProvClassNode node) {
    return new Contains(this.getId(), node);
  }

  // Getters
  public Long getId() {
    return this.id;
  }

  public BaseProvClassNode getNode() {
    return this.node;
  }
}
