package org.commonprovenance.framework.store.persistence.metaComponent.model.relation;

import org.commonprovenance.framework.store.persistence.metaComponent.model.node.EntityNode;
import org.springframework.data.annotation.PersistenceCreator;
import org.springframework.data.neo4j.core.schema.GeneratedValue;
import org.springframework.data.neo4j.core.schema.Id;
import org.springframework.data.neo4j.core.schema.RelationshipProperties;
import org.springframework.data.neo4j.core.schema.TargetNode;

@RelationshipProperties
public final class Used {

  @Id
  @GeneratedValue
  private final Long id;

  @TargetNode
  private final EntityNode entity;

  // Constructor for full initialization (used by Neo4j when reading)
  @PersistenceCreator
  public Used(Long id, EntityNode entity) {
    this.id = id;
    this.entity = entity;
  }

  // Constructor for creating new relationships (id will be generated)
  public Used(EntityNode entity) {
    this.id = null; // id will be generated by Neo4j
    this.entity = entity;
  }

  // Wither methods for immutability
  public Used withId(Long id) {
    return new Used(id, this.getEntity());
  }

  public Used withEntity(EntityNode entity) {
    return new Used(this.getId(), entity);
  }

  // Getters
  public Long getId() {
    return this.id;
  }

  public EntityNode getEntity() {
    return this.entity;
  }
}
