package org.commonprovenance.framework.store.persistence.metaComponent.model.relation;

import org.commonprovenance.framework.store.persistence.metaComponent.model.node.AgentNode;
import org.springframework.data.annotation.PersistenceCreator;
import org.springframework.data.neo4j.core.schema.GeneratedValue;
import org.springframework.data.neo4j.core.schema.Id;
import org.springframework.data.neo4j.core.schema.RelationshipProperties;
import org.springframework.data.neo4j.core.schema.TargetNode;

@RelationshipProperties
public final class WasAssociatedWith {

  @Id
  @GeneratedValue
  private final Long id;

  @TargetNode
  private final AgentNode agent;

  // Constructor for full initialization (used by Neo4j when reading)
  @PersistenceCreator
  public WasAssociatedWith(Long id, AgentNode agent) {
    this.id = id;
    this.agent = agent;
  }

  // Constructor for creating new relationships (id will be generated)
  public WasAssociatedWith(AgentNode agent) {
    this.id = null; // id will be generated by Neo4j
    this.agent = agent;
  }

  // Wither methods for immutability
  public WasAssociatedWith withId(Long id) {
    return new WasAssociatedWith(id, this.getAgent());
  }

  public WasAssociatedWith withAgent(AgentNode agent) {
    return new WasAssociatedWith(this.getId(), agent);
  }

  // Getters
  public Long getId() {
    return this.id;
  }

  public AgentNode getAgent() {
    return this.agent;
  }
}
