package org.commonprovenance.framework.store.persistence.metaComponent.model.relation;

import org.commonprovenance.framework.store.persistence.metaComponent.model.node.AgentNode;
import org.springframework.data.annotation.PersistenceCreator;
import org.springframework.data.neo4j.core.schema.GeneratedValue;
import org.springframework.data.neo4j.core.schema.Id;
import org.springframework.data.neo4j.core.schema.RelationshipProperties;
import org.springframework.data.neo4j.core.schema.TargetNode;

@RelationshipProperties
public final class WasAttributedTo {

  @Id
  @GeneratedValue
  private final String id;

  @TargetNode
  private final AgentNode agent;

  // Constructor for full initialization (used by Neo4j when reading)
  @PersistenceCreator
  public WasAttributedTo(String id, AgentNode agent) {
    this.id = id;
    this.agent = agent;
  }

  // Constructor for creating new relationships (id will be generated)
  public WasAttributedTo(AgentNode agent) {
    this.id = null; // id will be generated by Neo4j
    this.agent = agent;
  }

  // Wither methods for immutability
  public WasAttributedTo withId(String id) {
    return new WasAttributedTo(id, this.getAgent());
  }

  public WasAttributedTo withAgent(AgentNode agent) {
    return new WasAttributedTo(this.getId(), agent);
  }

  // Getters
  public String getId() {
    return this.id;
  }

  public AgentNode getAgent() {
    return this.agent;
  }
}
