package org.commonprovenance.framework.store.persistence.metaComponent.model.relation;

import org.commonprovenance.framework.store.persistence.metaComponent.model.node.ActivityNode;
import org.springframework.data.annotation.PersistenceCreator;
import org.springframework.data.neo4j.core.schema.GeneratedValue;
import org.springframework.data.neo4j.core.schema.Id;
import org.springframework.data.neo4j.core.schema.RelationshipProperties;
import org.springframework.data.neo4j.core.schema.TargetNode;

@RelationshipProperties
public final class WasGeneratedBy {

  @Id
  @GeneratedValue
  private final Long id;

  @TargetNode
  private final ActivityNode activity;

  // Constructor for full initialization (used by Neo4j when reading)
  @PersistenceCreator
  public WasGeneratedBy(Long id, ActivityNode activity) {
    this.id = id;
    this.activity = activity;
  }

  // Constructor for creating new relationships (id will be generated)
  public WasGeneratedBy(ActivityNode activity) {
    this.id = null; // id will be generated by Neo4j
    this.activity = activity;
  }

  // Wither methods for immutability
  public WasGeneratedBy withId(Long id) {
    return new WasGeneratedBy(id, this.getActivity());
  }

  public WasGeneratedBy withActivity(ActivityNode activity) {
    return new WasGeneratedBy(this.getId(), activity);
  }

  // Getters
  public Long getId() {
    return this.id;
  }

  public ActivityNode getActivity() {
    return this.activity;
  }
}
