package org.commonprovenance.framework.store.persistence.relation;

import org.commonprovenance.framework.store.persistence.entity.DocumentEntity;
import org.springframework.data.annotation.PersistenceCreator;
import org.springframework.data.neo4j.core.schema.GeneratedValue;
import org.springframework.data.neo4j.core.schema.Id;
import org.springframework.data.neo4j.core.schema.RelationshipProperties;
import org.springframework.data.neo4j.core.schema.TargetNode;

import jakarta.validation.constraints.NotNull;

@RelationshipProperties
public final class BelongsTo {

  @Id
  @GeneratedValue
  private final Long id;

  @TargetNode
  private final DocumentEntity document;

  // Constructor for full initialization (used by Neo4j when reading)
  @PersistenceCreator
  public BelongsTo(Long id, DocumentEntity documentEntity) {
    this.id = id;
    this.document = documentEntity;
  }

  // Constructor for creating new relationships (id will be generated)
  public BelongsTo(DocumentEntity documentEntity) {
    this.id = null; // id will be generated by Neo4j
    this.document = documentEntity;
  }

  // Wither methods for immutability
  public @NotNull BelongsTo withId(Long id) {
    return new BelongsTo(id, this.getDocument());
  }

  public @NotNull BelongsTo withDocument(@NotNull DocumentEntity documentEntity) {
    return new BelongsTo(this.getId(), documentEntity);
  }

  // Getters

  public Long getId() {
    return this.id;
  }

  public DocumentEntity getDocument() {
    return this.document;
  }
}
