package org.commonprovenance.framework.store.persistence.relation;

import org.commonprovenance.framework.store.model.TrustedParty;
import org.commonprovenance.framework.store.persistence.entity.TrustedPartyEntity;
import org.commonprovenance.framework.store.persistence.entity.factory.EntityFactory;
import org.springframework.data.neo4j.core.schema.GeneratedValue;
import org.springframework.data.neo4j.core.schema.Id;
import org.springframework.data.neo4j.core.schema.RelationshipProperties;
import org.springframework.data.neo4j.core.schema.TargetNode;

import jakarta.validation.constraints.NotNull;

@RelationshipProperties
public final class Trusts {

  @Id
  @GeneratedValue
  private final Long id;

  @TargetNode
  private final TrustedPartyEntity trustedParty;

  // 1) Constructor used when writing TO Neo4j
  public Trusts(TrustedParty model) {
    this.id = null; // Auto-generated by Neo4j
    this.trustedParty = EntityFactory.toEntity(model).blockOptional().orElse(null);
  }

  // 2) Constructor used when reading FROM Neo4j
  public Trusts(TrustedPartyEntity trustedParty) {
    this.id = null; // Auto-generated by Neo4j
    this.trustedParty = trustedParty;
  }

  // 3) Constructor for full initialization (used by Neo4j when reading)
  public Trusts(Long id, TrustedPartyEntity trustedParty) {
    this.id = this.getId();
    this.trustedParty = trustedParty;
  }

  // Wither methods for immutability
  public @NotNull Trusts withId(Long id) {
    return new Trusts(id, this.getTrustedParty());
  }

  public @NotNull Trusts withTrustedParty(@NotNull TrustedPartyEntity trustedParty) {
    return new Trusts(this.getId(), trustedParty);
  }

  // Getters

  public Long getId() {
    return this.id;
  }

  public TrustedPartyEntity getTrustedParty() {
    return this.trustedParty;
  }
}
