# Create an organization

@organization_name=myorg_6


POST http://{{$dotenv STORE_HOST}}:{{$dotenv STORE_PORT}}/api/v1/organizations HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "name": "{{organization_name}}",
  "clientCertificate": "{{$dotenv CLIENT_CERT}}",
  "intermediateCertificates": [
    "{{$dotenv INTERMEDIATE_CERT_1}}",
    "{{$dotenv INTERMEDIATE_CERT_2}}"
    ],
  "clearancePeriod": 30
}