package org.commonprovenance.framework.store.persistence.finalizedProvComponent.model.relation;

import org.commonprovenance.framework.store.persistence.finalizedProvComponent.model.node.DocumentNode;
import org.springframework.data.annotation.PersistenceCreator;
import org.springframework.data.neo4j.core.schema.GeneratedValue;
import org.springframework.data.neo4j.core.schema.Id;
import org.springframework.data.neo4j.core.schema.RelationshipProperties;
import org.springframework.data.neo4j.core.schema.TargetNode;

@RelationshipProperties
public final class BelongsTo {

  @Id
  @GeneratedValue
  private final String id;

  @TargetNode
  private final DocumentNode document;

  // Constructor for full initialization (used by Neo4j when reading)
  @PersistenceCreator
  public BelongsTo(String id, DocumentNode documentEntity) {
    this.id = id;
    this.document = documentEntity;
  }

  // Constructor for creating new relationships (id will be generated)
  public BelongsTo(DocumentNode documentEntity) {
    this.id = null; // id will be generated by Neo4j
    this.document = documentEntity;
  }

  // Wither methods for immutability
  public BelongsTo withId(String id) {
    return new BelongsTo(id, this.getDocument());
  }

  public BelongsTo withDocument(DocumentNode documentEntity) {
    return new BelongsTo(this.getId(), documentEntity);
  }

  // Getters

  public String getId() {
    return this.id;
  }

  public DocumentNode getDocument() {
    return this.document;
  }
}
