package org.commonprovenance.framework.store.persistence.finalizedProvComponent.model.relation;

import org.commonprovenance.framework.store.persistence.finalizedProvComponent.model.node.DocumentNode;
import org.springframework.data.annotation.PersistenceCreator;
import org.springframework.data.neo4j.core.schema.GeneratedValue;
import org.springframework.data.neo4j.core.schema.Id;
import org.springframework.data.neo4j.core.schema.RelationshipProperties;
import org.springframework.data.neo4j.core.schema.TargetNode;

@RelationshipProperties
public final class Owns {

  @Id
  @GeneratedValue
  private final String id;

  @TargetNode
  private final DocumentNode document;

  // Constructor for full initialization (used by Neo4j when reading)
  @PersistenceCreator
  public Owns(String id, DocumentNode document) {
    this.id = id;
    this.document = document;
  }

  // Constructor for creating new relationships (id will be generated)
  public Owns(DocumentNode document) {
    this.id = null; // id will be generated by Neo4j
    this.document = document;
  }

  // Wither methods for immutability
  public Owns withId(String id) {
    return new Owns(id, this.getDocument());
  }

  public Owns withDocument(DocumentNode document) {
    return new Owns(this.getId(), document);
  }

  // Getters

  public String getId() {
    return this.id;
  }

  public DocumentNode getDocument() {
    return this.document;
  }
}
