package org.commonprovenance.framework.store.persistence.finalizedProvComponent.model.relation;

import org.commonprovenance.framework.store.persistence.finalizedProvComponent.model.node.TrustedPartyNode;
import org.springframework.data.annotation.PersistenceCreator;
import org.springframework.data.neo4j.core.schema.GeneratedValue;
import org.springframework.data.neo4j.core.schema.Id;
import org.springframework.data.neo4j.core.schema.RelationshipProperties;
import org.springframework.data.neo4j.core.schema.TargetNode;

@RelationshipProperties
public final class WasIssuedBy {

  @Id
  @GeneratedValue
  private final String id;

  @TargetNode
  private final TrustedPartyNode trustedParty;

  // Constructor for full initialization (used by Neo4j when reading)
  @PersistenceCreator
  public WasIssuedBy(String id, TrustedPartyNode trustedParty) {
    this.id = id;
    this.trustedParty = trustedParty;
  }

  // Constructor for creating new relationships (id will be generated)
  public WasIssuedBy(TrustedPartyNode trustedParty) {
    this.id = null; // id will be generated by Neo4j
    this.trustedParty = trustedParty;
  }

  // Wither methods for immutability
  public WasIssuedBy withId(String id) {
    return new WasIssuedBy(id, this.getTrustedParty());
  }

  public WasIssuedBy withTrustedParty(TrustedPartyNode trustedParty) {
    return new WasIssuedBy(this.getId(), trustedParty);
  }

  // Getters

  public String getId() {
    return this.id;
  }

  public TrustedPartyNode getTrustedParty() {
    return this.trustedParty;
  }
}
